#! /bin/sh

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting filetoast daemon"
    start-stop-daemon --start --exec /usr/bin/filetoast daemon --make-pidfile --pidfile /run/filetoast.pid --background
    ;;
  stop)
    echo "Stopping filetoast daemon"
    start-stop-daemon --stop --exec /usr/bin/filetoast
    ;;
  *)
    echo "Usage: /etc/init.d/filetoast {start|stop}"
    exit 1
    ;;
esac

exit 0
